prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix foaf: <http://xmlns.com/foaf/0.1/>
prefix rel: <http://purl.org/vocab/relationship/>

select ?url
where {
  ?person rel:childOf ?url ;
          foaf:givenname ?name .
}